stages:
- static-check
- build
- e2e
- deploy

# static check stage
lint:
  stage: static-check
  script: ./tbox lint
unit:
  stage: static-check
  script: ./tbox unit
codegen:
  stage: static-check
  script: ./tbox codegen

# build stage
build:
  stage: build
  script:
  - ./tbox minikube     # k8s 내부의 로컬 레지스트리를 사용하기 때문에 먼저 minikube 생성. 혹시 이전에 안지워졌어도 이 안에서 삭제함
  - ./tbox build

# e2e stage
e2e:
  stage: e2e
  script:
  - ./tbox e2e
  after_script:
  - ./tbox minikube_clean

# deploy stage for master (with latest)
deploy-latest:
  stage: deploy
  only:
    refs:
    - master
  script:
  - docker tag localhost:5000/kubevirt-image-service:canary quay.io/tmaxanc/kubevirt-image-service:latest
  - docker push quay.io/tmaxanc/kubevirt-image-service:latest

# deploy stage for release (with tag name)
deploy-release:
  stage: deploy
  only:
  - tags
  script:
  - docker tag localhost:5000/kubevirt-image-service:canary quay.io/tmaxanc/kubevirt-image-service:${CI_COMMIT_TAG}
  - docker push quay.io/tmaxanc/kubevirt-image-service:${CI_COMMIT_TAG}
