apiVersion: hypercloud.tmaxanc.com/v1alpha1
kind: VirtualMachineImage
metadata:
  name: myubuntu
spec:
  source:
    http: https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.0-i386-disk.img # qcow2 이미지의 http 경로
  snapshotClassName: csi-rbdplugin-snapclass # 스냅샷 프로비저닝을 위해 사용 할 CSI를 담은 객체(snapshotClass)의 이름
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "3Gi"
    storageClassName: rook-ceph-block
