apiVersion: hypercloud.tmaxanc.com/v1alpha1
kind: VirtualMachineImage
metadata:
  name: myubuntu
spec:
  source:
    http: https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.0-i386-disk.img
  snapshotClassName: csi-rbdplugin-snapclass
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "3Gi"
    storageClassName: rook-ceph-block
