apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinevolumes.hypercloud.tmaxanc.com
spec:
  group: hypercloud.tmaxanc.com
  names:
    kind: VirtualMachineVolume
    listKind: VirtualMachineVolumeList
    plural: virtualmachinevolumes
    shortNames:
    - vmv
    singular: virtualmachinevolume
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of VirtualMachineVolume
      jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VirtualMachineVolume is the Schema for the virtualmachinevolumes
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VirtualMachineVolumeSpec defines the desired state of VirtualMachineVolume
            properties:
              capacity:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: Capacity defines size of the VirtualMachineVolume
                type: object
              virtualMachineImage:
                description: VirtualMachineImage defines name of the VirtualMachineImage
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - virtualMachineImage
            type: object
          status:
            description: VirtualMachineVolumeStatus defines the observed state of
              VirtualMachineVolume
            properties:
              state:
                description: State is the current state of VirtualMachineVolume
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
