apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinevolumeexports.hypercloud.tmaxanc.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    description: Current state of VirtualMachineVolumeExport
    name: State
    type: string
  group: hypercloud.tmaxanc.com
  names:
    kind: VirtualMachineVolumeExport
    listKind: VirtualMachineVolumeExportList
    plural: virtualmachinevolumeexports
    shortNames:
    - vmve
    singular: virtualmachinevolumeexport
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualMachineVolumeExport is the Schema for the virtualmachinevolumeexports
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualMachineVolumeExportSpec defines the desired state of
            VirtualMachineVolumeExport
          properties:
            destination:
              description: VirtualMachineVolumeExportDestination defines the destination
                to export volume
              properties:
                local:
                  description: VirtualMachineVolumeExportDestinationLocal defines
                    the Local destination to export volume
                  type: object
              type: object
            virtualMachineVolume:
              description: VirtualMachineVolumeSource indicates the VirtualMachineVolume
                to be exported
              properties:
                name:
                  type: string
              required:
              - name
              type: object
          required:
          - destination
          - virtualMachineVolume
          type: object
        status:
          description: VirtualMachineVolumeExportStatus defines the observed state
            of VirtualMachineVolumeExport
          properties:
            errorMessage:
              description: Human-readable message indicating details about last transition.
              type: string
            readyToUse:
              type: boolean
            state:
              description: State is the current state of VirtualMachineVolumeExport
              type: string
          required:
          - state
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
