name: kubevirt-image-service
on:
  pull_request:
jobs:
  static:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: lint test
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
      - name: unit test
        run: ./testbox unit
      - name: codegen test
        run: ./testbox codgen
  e2e:
    needs: static
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: minikube start
        run: |
          ./testbox minikube download
          ./testbox minikube start
          ./testbox rook_install
      - name: build
        run: |
          ./testbox operator-sdk_install
          docker login -u=tmaxanc+robot -p=${{ secrets.QUAY_PASSWORD }} quay.io
          ./testbox build
      - name: e2e test
        run: ./testbox e2e
      - name: run debug mode ssh connection if failure
        if: ${{ failure() }}
        run: |
          curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
          sleep 1h       # Preventing to killing instance after failure
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.NGROK_USER_PASS }}
  deploy:
    needs: e2e
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ./testbox operator-sdk_install
          docker login -u=tmaxanc+robot -p=${{ secrets.QUAY_PASSWORD }} quay.io
          ./testbox build
      - name: push
        run: |
          docker tag quay.io/tmaxanc/kubevirt-image-service:canary quay.io/tmaxanc/kubevirt-image-service:latest
          docker push quay.io/tmaxanc/kubevirt-image-service:canary:latest
